<?php

namespace Fobia\Configuration;

use Fobia\Configuration\ConfigurationHandler;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-17 at 13:10:43.
 */
class ConfigurationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Configuration
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $cfg = array(
            'path1.to1' => 'value11',
            'path1.to2' => 'value12',
            'path2' => array(
                'to1' => 'value21'
            )
        );
        $this->object = new Configuration(new ConfigurationHandler());
        $this->object->setArray($cfg);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Fobia\Configuration\Configuration::setArray
     * @todo   Implement testSetArray().
     */
    public function testSetArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fobia\Configuration\Configuration::setDefaults
     * @todo   Implement testSetDefaults().
     */
    public function testSetDefaults()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fobia\Configuration\Configuration::getDefaults
     * @todo   Implement testGetDefaults().
     */
    public function testGetDefaults()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fobia\Configuration\Configuration::callHandlerMethod
     * @todo   Implement testCallHandlerMethod().
     */
    public function testCallHandlerMethod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fobia\Configuration\Configuration::offsetGet
     * @todo   Implement testOffsetGet().
     */
    public function testOffsetGet()
    {   
        $this->assertEquals('value11', $this->object['path1.to1']);
        $this->assertEquals('value21', $this->object['path2.to1']);
    }

    /**
     * @covers Fobia\Configuration\Configuration::offsetSet
     * @todo   Implement testOffsetSet().
     */
    public function testOffsetSet()
    {
        $this->object['path1.to3'] = 'value13';
        $this->assertEquals('value13', $this->object['path1.to3']);

        //$this->object['path1']['to4'] = 'value14';
        //$this->assertEquals('value14', $this->object['path1.to4']);
    }

    /**
     * @covers Fobia\Configuration\Configuration::offsetExists
     * @todo   Implement testOffsetExists().
     */
    public function testOffsetExists()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fobia\Configuration\Configuration::offsetUnset
     * @todo   Implement testOffsetUnset().
     */
    public function testOffsetUnset()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Fobia\Configuration\Configuration::getIterator
     * @todo   Implement testGetIterator().
     */
    public function testGetIterator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
